#! /bin/csh -f


set current_path = `pwd`
set tag_inn = `echo $current_path | awk -F/ '{print $(NF-3)}'`
set run_inn = `echo $current_path | awk -F/ '{print $(NF-1)}'`
set top_name = `echo $current_path | awk -F/ '{print $(NF-4)}'`
set base_path = `echo $current_path | awk -F "/works_" '{print $1}'`
set DK_VER = "dc-0.0_dk-0.0_tag-0.0"
set pnr_gds = ${top_name}.gds.gz
set MPnet = ${top_name}.lvs.v.gz
set outfeedDirName = "${base_path}/outfeeds/${top_name}/${tag_inn}/${run_inn}"
set ref_gds_path = "$base_path/db/vers/${DK_VER}/*/gds_oas"
set ref_cdl_path = "$base_path/db/vers/${DK_VER}/*/cdl"
set ref_pdk_path = "$base_path/db/vers/${DK_VER}/pdk/calibre_runset"






#set PVRUN  = `pwd`
#set top_name =  `echo $PVRUN | awk -F'/' '{print $7}'`
#set base_path = `echo $PVRUN | awk -F'/' '{print "/"$2"/"$3"/"$4"/"$5}'`
#set tag_inn =   `echo $PVRUN | awk -F'/' '{print $8}'`
#set run_inn =   `echo $PVRUN | awk -F'/' '{print $10}'`
#set DK_VER = "dc-0.0_dk-0.0_tag-0.0"
#set pnr_gds = ${top_name}.gds.gz
#set MPnet = ${top_name}.lvs.v.gz
#set outfeedDirName = "${base_path}/outfeeds/${top_name}/${tag_inn}/${run_inn}"
#set ref_gds_path = "$base_path/db/vers/${DK_VER}/*/gds_oas"
#set ref_cdl_path = "$base_path/db/vers/${DK_VER}/*/cdl"
#set ref_pdk_path = "$base_path/db/vers/${DK_VER}/pdk/calibre_runset"


echo "top_name      $top_name"
echo "base_path     $base_path"
echo "tag_inn       $tag_inn"
echo "run_inn       $run_inn"
echo "DK_VER        $DK_VER"
echo "pnr_gds       $pnr_gds"
echo "MPnet         $MPnet"
echo "outfeedDirName$outfeedDirName"
echo "ref_gds_path  $ref_gds_path"
echo "ref_cdl_path  $ref_cdl_path"
echo "ref_pdk_path  $ref_pdk_path"



while (! -e ${outfeedDirName}/innovus.done )

    echo "Wating for P&R GDS"
    echo "Wating file :${outfeedDirName}/innovus.done "
    sleep 60
end



#--------------------------------------------------------------------------------Copy RULE Script
    mkdir -p 00_GDS
    cp -rf ${ref_pdk_path}/GDS/* 00_GDS
#------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------Go Pv
    cd 00_GDS
#------------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------Update Rule Deck ENV
sed -i 's|set topcell.*|set topcell '${top_name}'|g' mergeBlock.tcl
sed -i 's|set input_gds.*|set input_gds '${outfeedDirName}/gds/${pnr_gds}'|g' mergeBlock.tcl
sed -i "s|set ip_gds_path.*|set ip_gds_path ${ref_gds_path}|g" mergeBlock.tcl
sed -i 's|set output_name.*|set output_name "merged_'${pnr_gds}'"|g' mergeBlock.tcl
#------------------------------------------------------------------------------------------


#---------------------------------------------------------------------------------Excute Run
source :run
#------------------------------------------------------------------------------------------


exit
