LEF_FILE: *.tech.lef *.lef
TOP_DEF_FILE: *.def

MAPPING_FILE: /mnt/data/prjs/ANA6710P/pd/library/NXTGRD/G-DF-EHV28N-1P8M2A-LP_STARRCXT-LPE.map

SIMULTANEOUS_MULTI_CORNER: YES
CORNERS_FILE: ./corner_configFile.smc
SELECTED_CORNERS: p125c_cmax m40c_cmax  m40c_rcmin                      m40c_cmin  p125c_cmin p125c_rcmax                     p25c_typical

REFERENCE_DIRECTION: VERTICAL
DPT: YES
NETLIST_FILE: /mnt/data/prjs/ANA6714/outfeeds/dsc_decode/pd___dc-0.0_dk-0.0_tag-0.0/01_dcg_241120-09_Update_Script-fe00_te00_pv00/spef/dsc_decode.spef.gz
NETLIST_FORMAT: spef
NETLIST_COMPRESS_COMMAND: gzip

SKIP_CELLS: *

COUPLING_ABS_THRESHOLD: 1e-15
COUPLING_REL_THRESHOLD: 0.01

***COUPLING_REPORT_NUMBER : COUPLING_NUM
***COUPLING_REPORT_FILE : coup_full.rpt
NETLIST_NODE_SECTION: YES
NETLIST_INPUT_DRIVERS: YES
NETLIST_CONNECT_OPENS: *

REMOVE_DANGLING_NETS : NO
NETLIST_MAX_LINE: 500

COUPLE_TO_GROUND: NO
EXTRACT_VIA_CAPS: YES

REDUCTION: NO_EXTRA_LOOPS
ENHANCED_SHORT_REPORTING : YES

***REMOVE_METAL_FILL_OVERLAP: NO
***MILKYWAY_ADDITIONAL_VIEWS: FILL
METAL_FILL_POLYGON_HANDLING: FLOATING

STAR_DIRECTORY: ./log/star

REPORT_METAL_FILL_STATISTICS : NO
NUM_CORES : 8
STARRC_DP_STRING: list localhost:8


LEF_USE_OBS: YES
